### ISSUE TITLE
libvorbis-1.4.0 does not exist yet

### ISSUE THREAD

**Issue by c-yan** [AO-Yumi/vorbis_aotuv#1]
Although the following README refers to libvorbis-1.4.0, the latest libvorbis is 1.3.6, so it does not seem to exist.

https://github.com/AO-Yumi/vorbis_aotuv/blob/master/win32/VS2010/README#L7

I imagine writing mistakes in libvorbis-1.3.6 or vorbis-tools-1.4.0.
How about that?

**Comment by AO-Yumi** [comment]
Let's wait libvorbis-1.4.0!

**Comment by c-yan** [comment]
Looks like the latest is still 1.3.7!

**Comment by AO-Yumi** [comment]
I think we have a long way to go, so I fixed it.

**Comment by c-yan** [comment]
I have confirmed the fix and will close this ticket. Note that if you write something like "close #1" in the commit message, this will be closed automatically.

**Comment by AO-Yumi** [comment]
Thanks for the info.
