### ISSUE TITLE
rebase on v1.3.7

### ISSUE THREAD

**Issue by andrius4669** [AO-Yumi/vorbis_aotuv#2]
https://github.com/xiph/vorbis/releases/tag/v1.3.7 was released 2 days ago

**Comment by andrius4669** [comment]
https://hydrogenaud.io/index.php?topic=115774.0

**Comment by AO-Yumi** [comment]
Thank you for waiting. I released 2020 version now.

**Comment by andrius4669** [comment]
Thank you!

**Comment by sergeevabc** [comment]
Dear @AO-Yumi, how are you? You haven't appeared on Hydrogen since 2011.
